### ISSUE TITLE
KeyError: 'SUMLATION'

### ISSUE THREAD

**Issue by youngjae41** [mzahana/px4_octune_ros#2]
Hello

Thanks for sharing good code 

I'm testing this source but getting an error

![제목 없음1](https://user-images.githubusercontent.com/55374072/200210086-b074440b-81f0-49da-bedb-9623ff497e7a.png)

**Comment by mzahana** [comment]
Hi @youngjae41 
Thank you for trying out the code. The code is related to a journal publication submitted to *Sensors*. It will be maintained once the publication is accepted.

Thanks.

**Comment by youngjae41** [comment]
@mzahana Ok Thanks!

**Comment by mzahana** [comment]
@youngjae41 The work is now published here: https://doi.org/10.3390/s22239240

Regarding your error. Just set the environment variable `SIMULATION=true`. You can do this in the terminal where you run the simulation as follows.
```
export SIMULATION=true
```
 if you are running this in simulation. Otherwise, set it to `false`.

**Comment by youngjae41** [comment]
@mzahana Thanks !!

but this error 
![image](https://user-images.githubusercontent.com/55374072/204702628-b4bb6960-4b15-41d6-85aa-31a237be08bd.png)
[ERROR] [1669779598.468648, 244.064000]: Data buffering timedout dt= 2.104387044906616 > 2.1. Aborting tuning process

**Comment by mzahana** [comment]
@youngjae41 this is a different error. Kindly, open a different issue for it. Thanks.
